### ISSUE TITLE
Feed results in hanging up emacs

### ISSUE THREAD

**Issue by brabalan** [skeeto/elfeed#39] opened 2014-07-13 08:41 UTC
(Edit: I'm getting rid of the byte-code stuff as github does not like it).

When I try to update this feed https://www.gaslampgames.com/feed/ an exception is triggered then emacs hangs, until I manage to "C-c" or "C-g" a few times.

This is the backtrace I'm getting:

```
Debugger entered--Lisp error: (error "gaslampgames.comfeed/443 nodename nor servname provided, or not known")
  make-network-process(:name "gaslampgames.comfeed" :buffer #<buffer  *url-http-temp*> :host "gaslampgames.comfeed" :service 443 :nowait nil)
  open-network-stream("gaslampgames.comfeed" #<buffer  *url-http-temp*> "gaslampgames.comfeed" 443)
  open-gnutls-stream("gaslampgames.comfeed" #<buffer  *url-http-temp*> "gaslampgames.comfeed" 443)
  network-stream-open-tls("gaslampgames.comfeed" #<buffer  *url-http-temp*> "gaslampgames.comfeed" 443 (:type tls :nowait t))
  open-network-stream("gaslampgames.comfeed" #<buffer  *url-http-temp*> "gaslampgames.comfeed" 443 :type tls :nowait t)
  byte-code("..." [coding-system-for-write coding-system-for-read gw-method name buffer host binary (tls ssl native) native plain open-network-stream :type :nowait featurep make-network-process (:nowait t) socks socks-open-network-stream telnet url-open-telnet rlogin url-open-rlogin error "Bad setting of url-gateway-method: %s" service url-gateway-method conn] 11)
  url-open-stream("gaslampgames.comfeed" #<buffer  *url-http-temp*> "gaslampgames.comfeed" 443)
  url-http-find-free-connection("gaslampgames.comfeed" 443)
  url-http([cl-struct-url "https" nil nil "gaslampgames.comfeed" nil "/" nil nil t :silent t] #[..." [..." ["http://gaslampgames.com/feed/" print-escape-newlines :error t message "Elfeed update failed for %s: %S" err funcall make-byte-code 0 " ... vconcat vector [url-http-end-of-headers set-buffer-multibyte t elfeed-xml-parse-region elfeed-feed-type eql :atom elfeed-entries-from-atom :rss elfeed-entries-from-rss :rss1\.0 elfeed-entries-from-rss1\.0 error "Unknown feed type." elfeed-db-add] 5 "\n\n(fn)" error 257 "\..." [message "Elfeed update failed for %s: %s"] "\n\n(fn ERROR)" kill-buffer] 11 "\n\n(fn STATUS)"] funcall make-byte-code 0 "..." vconcat vector [elfeed-connections cl-delete :key car elfeed--check-queue] 5 "\n\n(fn)"] 8 "\n\n(fn STATUS)"] ((:redirect "https://gaslampgames.comfeed/")))
  url-https([cl-struct-url "https" nil nil "gaslampgames.comfeed" nil "/" nil nil t :silent t] #[..." ["http://gaslampgames.com/feed/" print-escape-newlines :error t message "Elfeed update failed for %s: %S" err funcall make-byte-code 0 "  ..." vconcat vector [url-http-end-of-headers set-buffer-multibyte t elfeed-xml-parse-region elfeed-feed-type eql :atom elfeed-entries-from-atom :rss elfeed-entries-from-rss :rss1\.0 elfeed-entries-from-rss1\.0 error "Unknown feed type." elfeed-db-add] 5 "\n\n(fn)" error 257 "..." [message "Elfeed update failed for %s: %s"] "\n\n(fn ERROR)" kill-buffer] 11 "\n\n(fn STATUS)"] funcall make-byte-code 0 "..." vconcat vector [elfeed-connections cl-delete :key car elfeed--check-queue] 5 "\n\n(fn)"] 8 "\n\n(fn STATUS)"] ((:redirect "https://gaslampgames.comfeed/")))
  url-retrieve-internal("https://gaslampgames.comfeed/" #[257 "..." ["http://gaslampgames.com/feed/" print-escape-newlines :error t message "Elfeed update failed for %s: %S" err funcall make-byte-code 0 "    ..." vconcat vector [url-http-end-of-headers set-buffer-multibyte t elfeed-xml-parse-region elfeed-feed-type eql :atom elfeed-entries-from-atom :rss elfeed-entries-from-rss :rss1\.0 elfeed-entries-from-rss1\.0 error "Unknown feed type." elfeed-db-add] 5 "\n\n(fn)" error 257 "..." [message "Elfeed update failed for %s: %s"] "\n\n(fn ERROR)" kill-buffer] 11 "\n\n(fn STATUS)"] funcall make-byte-code 0 "..." vconcat vector [elfeed-connections cl-delete :key car elfeed--check-queue] 5 "\n\n(fn)"] 8 "\n\n(fn STATUS)"] ((:redirect "https://gaslampgames.comfeed/")) :silent nil)
  url-http-parse-headers()
  url-http-content-length-after-change-function(279 599 320)
  url-http-wait-for-headers-change-function(1 609 608)
  url-http-generic-filter(#<process gaslampgames.com> "HTTP/1.1 301 Moved Permanently
\nDate: Sun, 13 Jul 2014 08:26:57 GMT
\nServer: Apache/2.2.22 (Debian)
\nLocation: https://gaslampgames.comfeed/
\nVary: Accept-Encoding
\nContent-Length: 319
\nKeep-Alive: timeout=5, max=100
\nConnection: Keep-Alive
\nContent-Type: text/html; charset=iso-8859-1
\n
\n<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>301 Moved Permanently</title>\n</head><body>\n<h1>Moved Permanently</h1>\n<p>The document has moved <a href=\"https://gaslampgames.comfeed/\">here</a>.</p>\n<hr>\n<address>Apache/2.2.22 (Debian) Server at gaslampgames.com Port 80</address>\n</body></html>\n")
```

I find the missing `/` in the redirection strange. When I nagivate to the https://www.gaslampgames.com/feed/ url using Firefox, it's showing me a feed and proposing to subscribe to it.

Is this a bug in elfeed or in their feed?

**Comment by runswithd6s** [comment] 2015-04-13 20:05
Is there a way to drop this into an async process? I am also getting blocking w/in Emacs when bad feeds are being parsed.

**Comment by Fuco1** [comment] 2015-09-10 20:54
Elfeed started blocking my emacs too since I updated to 24.5... now I have to restart almost daily.  I run exact same setup at work without elfeed and it has been running flawlessly for 2 months now.  I can't tell if the issue here is the same and I don't know how to debug it as it just completely locks emacs.

**Comment by seanleblanc** [comment] 2015-10-15 00:25
I am having the same issue - it locks Emacs up, and I have to kill and restart.

**Comment by seanleblanc** [comment] 2015-10-19 23:56
FWIW, it seems the url in question was BoingBoing's feed:
http://boingboing.net/feed

Once I took that out of my list, it seems better?

**Comment by skeeto** [comment] 2015-10-20 00:41
@seanleblanc Is it also Emacs 24.5 for you? I use 24.4 day-to-day
(Debian) and haven't seen this issue. Since you gave me the BoingBoing
feed as a specific example, I built Emacs 24.5.2 and gave it a whirl
with no other configuration, but I'm still unable to reproduce.


    $ emacs --version
    GNU Emacs 24.5.2
    $ mkdir /tmp/test
    $ HOME=/tmp/test emacs -L . -l elfeed.el \
          --eval '(elfeed-add-feed "http://boingboing.net/feed")' \
          -f elfeed

**Comment by seanleblanc** [comment] 2015-10-21 04:20
M-x emacs-version:

GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org


...but now I cannot replicate it either? Happened fairly regularly before: I would enter elfeed, and hit G to refresh. If it didn't happen on first one, it happened on the second. But now it doesn't happen, if with many refreshes? Not sure what might have changed between when I posted that and now.

**Comment by kjw** [comment] 2015-12-20 14:22
Same issue here. I just started using elfeed (love it!) on emacs 24.5.1 / OSX and this is the one frustration I have. Every feed refresh hangs emacs. Not sure exactly which feed(s) in my feed list are causing the problem but I see TLS failed messages for several of them.

**Comment by heikkil** [comment] 2016-01-21 07:28
An other me-too. Running Emacs GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org

It has been getting worse but I have not been able to get to the bottom of it its cause. A few observations:

* I am getting a lot of timeouts
* elfeed hangs not only on update but also n retrieving entry content, especially images
* I am having most problems when network connection comes from cellular data
* I am also having problems with paradox. It is almost impossible to get an update. `package-list-packages` works always.
* `Crtl-G` sometimes gets me out of hanged process. Best way is to run `pkill -SIGUSR2 -i Emacs` from command line.

Clearly, the problem is not in elfeed but deeper in the way emacs handles http connections (somewhere in `url-*.el` files).

I hope this helps to point someone to find a fix.

**Comment by kjw** [comment] 2016-01-26 12:00
Solved my problem by compiling emacs with `--with-gnu-tls`.

**Comment by heikkil** [comment] 2016-01-28 07:59
`--with-gnutls` solved it!. I was using emacsformacosx, now compiled my own emacs using homebrew. Thanks!

**Comment by Fuco1** [comment] 2016-01-28 10:48
Hmm, I fail to see the relation of tls to the feeds (most of mine don't use https), but I'll try this as well, nothing to lose :P

**Comment by Andre0991** [comment] 2016-01-28 22:10
`--with-gnutls` did the trick for me. Thanks, kjw.

**Comment by Fuco1** [comment] 2016-01-30 13:30
When I run `./configure --help` on emacs 24.5 I don't have that option.  Am I missing some library?

**Comment by skeeto** [comment] 2016-01-30 14:54
You should see "--without-gnutls" listed in the --help, since
"--with-gnutls" is on by default. Unfortunately giving "--with-gnutls"
to ./configure will not cause it to fail, or even warn you that there's
a problem, if it can't find libgnutls (IMHO a bug), so you need to
verify it in the summary output at the end ("Does Emacs use -lgnutls?").

**Comment by Fuco1** [comment] 2016-01-30 15:01
I looked at the `config.log` from my original compilation and it says "yes", just as on the new run where I added the `--with-gnutls` (useless) switch.

When I check inside emacs with `(gnutls-available-p)` it gives me `t`.  So I think that this might not be related to the issue.

I am on Linux, it seems like the people above (at least some) use macos, maybe the issue is different there?

**Comment by Andre0991** [comment] 2016-01-30 20:50
> I am on Linux, it seems like the people above (at least some) use macos, maybe the issue is different there?

I think so. I'm using the `emacs-mac` build.

Also, I don't think this has to do with https feeds. Elfeed was hanging up on http feeds here, but for some reason installing `gnutls` did the trick - perhaps it handles http too, I don't know.

**Comment by Fuco1** [comment] 2016-03-02 18:33
Would it be possible to use `async` to run the update in the background?  We can have a timer in the main emacs and kill the subprocess if it hangs.

@skeeto do you think it would be possible? I would give it some time if the architecture is reasonably permitting to such a change---I don't know the internals that well.

**Comment by skeeto** [comment] 2016-03-09 15:20
This is something I've considered but haven't gotten around to trying.
Fetching and parsing in a separate process and sending back the complete
s-expression result would solve a lot of issues, making Elfeed more
pleasant to use. It would cover up most of Emacs networking and XML
parsing woes, since the subprocess could be killed if it takes too long
regardless of how it locked up. It would also work around the sporadic
segfaults related to opening parallel network connections.

That's why it's on the roadmap in the README.

**Comment by raamdev** [comment] 2016-03-16 01:29
`--with-gnutls` solved the issue of Elfeed freezing Emacs while refreshing feeds for me too. 

I'm on OS X and use Homebrew, so I just had to do the following:

```
$ brew update
$ brew unlink emacs
$ brew uninstall emacs
$ brew install --with-cocoa --srgb --with-gnutls emacs
$ brew linkapps emacs
```

**Comment by yuvallanger** [comment] 2017-05-02 09:41
I want to add that the hanging problem is also associated with CPU usage reaching 100%.

**Comment by skeeto** [comment] 2018-05-08 19:01
Closing since this should be fixed by the switch to the curl backend: [Elfeed, cURL, and You](https://nullprogram.com/blog/2016/06/16/)

**Closed by skeeto** 2018-05-08 19:01 UTC
