### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by gour** [skeeto/elfeed#154] opened 2016-02-18 09:53 UTC
Hello,

I'm using Elfeed with Spacemacs-0.105.9 along with elfeed-org to organize my list of feeds.

Everything was working nicely - actually, due to Elfeed I was enthusiastic to move other parts of my previous vim/Evo/taskwarrior setup to Emacs/Gnus/org-mode since it's very nice and the best RSS reader in Emacs-world, but since few days ago, when I added some feeds, I experience that launching Elfeed consumes all my cpu resources and I even notice that due to Emacs process my OS (Debian Sid x86_64) is using swap on the machine with 16GB of RAM.

As soon as I kill it with Ctrl-G, everything returns to normal.

I've tried to rm my elfeed database and start from the scratch, but same thing.

Do you have any advice how to troubleshoot it and/or or provide more useful details for you?

**Comment by skeeto** [comment] 2016-02-19 23:08
How big is ~/.elfeed/index? Does it happen when you start Elfeed? When
you update the feeds you just added? Are you adding them through
elfeed-add-feed (which automatically fetches)?

Elfeed reads the entire index when loaded. There's a *possibility* that
one of the feeds you follow dumped millions of entries on you, or used
some kind of bogus metadata (e.g. title), and it's blown up the index.
But this would be easily as noticable when that feed was fetched.

If ~/.elfeed/index *is* really large, you can try viewign it as a text
file to look for anything odd going on. It's just a large s-expression.

**Comment by gour** [comment] 2016-02-20 09:04
> How big is ~/.elfeed/index? 

355K

> Does it happen when you start Elfeed? When you update the feeds you just added? 

It happens when I do 'g r', iow. updating feeds.

> Are you adding them through elfeed-add-feed (which automatically fetches)? 

No, I add them by adding entry in my elfeed.org file

>Elfeed reads the entire index when loaded. There's a *possibility* that one of the feeds you follow dumped millions of entries on you, or used some kind of bogus metadata (e.g. title), and it's blown up the index. But this would be easily as noticable when that feed was fetched.

I noticed strange thing when I added feed for Debian's Sid new packages, but then I rm-ed that entry as well as the whole `data/ & index`, but the problem did not go away.

I'll try to inspect my 'index' to see if there is something visibly (to me) wrong there...

**Comment by gour** [comment] 2016-02-20 10:38
Of course, I can send you the whole ~/.elfeed - it's 670K *.xz file...

**Comment by gour** [comment] 2016-02-23 22:27
> If ~/.elfeed/index *is* really large

What is considered as large index?

**Comment by skeeto** [comment] 2016-02-24 02:14
One of mine is 19MB and works fine. It takes less than a second to load
and write, so it can probably stand to increase another order of
magnitude before it starts to become unwieldy. An index less than a MB
is still small.

If you send me your index file I'll take a look at it. The rest of the
content under .elfeed/ doesn't matter. I'd also like to see your
elfeed-feeds (which is not stored in the index).

**Comment by gour** [comment] 2016-02-24 09:10
> If you send me your index file I'll take a look at it.

Attached.
[index.zip](https://github.com/skeeto/elfeed/files/144183/index.zip)

> I'd also like to see your elfeed-feeds (which is not stored in the index).

Here it  is:

```
(("http://statusblog.webfaction.com/feed/" web)
 ("https://community.webfaction.com/feeds/rss" web)
 ("http://blog.webfaction.com/feed/" web)
 ("http://responsive.rga.com/rss" web)
 ("https://getgrav.org/blog.atom" web)
 ("http://feeds.feedburner.com/CssTricks" web)
 ("http://practicaltypography.com/feed.xml" web)
 ("http://alistapart.com/site/rss" web)
 ("http://www.tiobe.com/content/paperinfo/tpci/rss" misc)
 ("https://www.reddit.com/r/spacemacs/.rss" misc)
 ("http://blog.racket-lang.org/feeds/posts/default" misc)
 ("http://programming.reddit.com/.rss" misc)
 ("http://owncloud.org/blogfeed" misc)
 ("http://www.openshotvideo.com/feeds/posts/default" misc)
 ("http://freepages.modula2.org/rss/fmp.rss" misc)
 ("https://www.reddit.com/r/emacs/.rss" misc)
 ("https://duck.co/blog/rss" misc)
 ("http://changelog.complete.org/feed" misc)
 ("http://blog.bitbucket.org/feed/" misc)
 ("http://www.atmarama.org/rss/?section=blog" hare_krishna)
 ("http://stephenknapp.wordpress.com/feed/" hare_krishna)
 ("http://www.shyamasundaradasa.com/jyotish/feeds/" hare_krishna)
 ("https://www.reddit.com/r/emacs/.rss" hare_krishna)
 ("http://portal.vvz.hr/rss.php" hare_krishna)
 ("http://www.dandavats.com/?feed=rss2" hare_krishna)
 ("https://www.atmarama.net/rss.xml" hare_krishna)
 ("http://akincana.net/rss/" hare_krishna))
```

Btw, I'm using Spacemacs and elfeed-org and setup includes this:

```
(setq elfeed-max-connections 10)
(setq url-queue-timeout 30)
```

**Comment by skeeto** [comment] 2016-02-24 14:22
Ok, I've narrowed it down to a known Emacs bug which has been a thorn in
Elfeed's side in the past. This is a duplicate of #17 (Emacs bug
#16344). Here's the problem "feed":

http://www.tiobe.com/content/paperinfo/tpci/rss

Fortunately it's not actually a feed at all, so it's not something that
requires a workaround. The HTML comments at the beginning of the
document lock up Emacs' xml-parse-region. I narrowed it down to these
characters:

    (require 'xml)
    (with-temp-buffer
      (insert "<!--><s><")
      (xml-parse-region))
    ;; never completes

The freeze you're seeing is Emacs choking on parsing this document.

The actual feed is here:

http://www.tiobe.com/tiobe_index?page=rss

A number of the URLs in your list aren't actually feeds but rather pages
that link to feeds. You'll see the errors for these in *elfeed-log*. You
should switch these to the actual feed URLs. The confusion probably that
other Atom/RSS readers will find the proper feed URL from the HTML's
metadata and use it instead. Elfeed doesn't do this.

**Comment by skeeto** [comment] 2016-02-24 14:23
Close as duplicate of #17.

**Closed by skeeto** 2016-02-24 14:23 UTC

**Comment by gour** [comment] 2016-02-24 18:57
> Fortunately it's not actually a feed at all, so it's not something that requires a workaround. 

So, the solution is to just avoid that feed?

> A number of the URLs in your list aren't actually feeds but rather pages that link to feeds. You'll see the errors for these in *elfeed-log*. 

Ok, I'll inspect it...

**Comment by skeeto** [comment] 2016-02-24 20:31
> So, the solution is to just avoid that feed?

The actual feed isn't a problem. Trying to parse the HTML page as if it
were feed is the problem: 1) because it's HTML, not RSS or Atom, so
you'll never get anything out of it, and 2) the xml-parse-region bug
hangs up Emacs trying to parse that HTML as XML, breaking Elfeed.

Fixing the other problem I mentioned is as simple as visiting each of
the URLs in your elfeed-feeds list in you web browser. If it looks like
a web page, find the RSS or Atom feed URL for that page and use it
instead.

**Comment by gour** [comment] 2016-02-28 09:25
Thanks a lot...Everything is fine now. ;)
